version: "3.7"

services:
  web:
    container_name: "organization-administration-api"

    build:
      context: .
      target: development

    volumes:
      - "./src:/home/node/app/src"

    environment:
      DB_URL: mongo-db
      DB_PORT: 27017
      DB_NAME: "qsaas"

    depends_on:
      - mongo-db

    ports:
      - "${SERVER_PORT}:80"

    networks:
      - rabbitmq-net

    command: "npm run dev"

  mongo-db:
    image: mongo

    restart: always

    networks:
      - rabbitmq-net

    volumes:
      - "mongodb:/data/db"

    logging:
      driver: none

volumes:
  mongodb:


networks:
  rabbitmq-net:
    driver: bridge
    name: rabbitmq-net
