version: "3.7"

services:
  node_and_jest:
    container_name: "organization-administration-jest"

    build:
      context: .
      target: testing

    environment:
      DB_URL: mongo-db
      DB_PORT: 27017
      DB_NAME: "qsaas"

    depends_on:
      - mongo-db

    ports:
      - "${SERVER_PORT}:80"

    command: "npm run test"

  mongo-db:
    image: mongo

    restart: always

    volumes:
      - "mongodb:/data/db"

volumes:
  mongodb:
