version: "3.7"

services:
  web:
    container_name: "organization-administration-api"

    build:
      context: .
      dockerfile: dev.Dockerfile

    volumes:
      - "./src:/home/node/app/src"

    environment:
      DB_URL: mongo-db
      DB_PORT: 27017
      DB_NAME: "qsaas"
      RABBIT_MQ_URL: amqp://myrabbitmq:5672

    depends_on:
      - mongo-db
      - myrabbitmq

    ports:
      - "${SERVER_PORT}:80"

    command: "npm run dev"

  mongo-db:
    image: mongo

    ports:
      - "27017:27017"

    restart: always

    volumes:
      - "mongodb:/data/db"

    logging:
      driver: none

  myrabbitmq:
    image: rabbitmq:3-management-alpine

    ports:
      - 5672:5672
      - 15672:15672 # HTTP management port, use guest/guest for logging in

    volumes:
      - "rabbitmq-data:/var/lib/rabbitmq"

volumes:
  mongodb:
  rabbitmq-data:
#networks:
#  rabbitmq-net:
#    driver: bridge
#    name: rabbitmq-net
