version: "3.7"

services:
  node_and_jest:
    container_name: "organization-administration-jest"

    build:
      context: .
      dockerfile: test.Dockerfile

    environment:
      - DB_URL=mongo-db
      - DB_PORT=27017
      - DB_NAME=qsaas_test
      - JWT_KEY=key
      - RABBIT_MQ_URL=amqp://myrabbitmq:5672
      - ENV

    depends_on:
      - mongo-db

    ports:
      - "${SERVER_PORT}:80"

    command: "npm run test"

  mongo-db:
    image: mongo

    logging:
      driver: none

    ports:
      - "27017:27017"

    restart: "no"
