version: '3.7'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine

    ports:
      - 5672:5672
      - 15672:15672 # HTTP management port, use guest/guest for logging in

    volumes:
      - "rabbitmq-data:/var/lib/rabbitmq"

volumes:
  rabbitmq-data:
