enum ResourceType {
  ORGANIZATION_EMPLOYEE = "ORGANIZATION_EMPLOYEE",
  ENDPOINT = "ENDPOINT",
  QUEUE_NODE = "QUEUE_NODE",
  QUEUE_SERVER = "QUEUE_SERVER",
  AUTHORIZATION_RULE = "AUTHORIZATION_RULE",
}

export default ResourceType;
