name: Build Client Account system docker image CI
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build docker image
        run: docker build ./Client-Account-System/ --file ./Client-Account-System/Dockerfile --tag client-account-system:$(date +%s)

  tests:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./Client-Account-System

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install NPM packages
        run: npm ci

      - name: Run eslint checks
        run: npm run lint

      - name: Run unit tests
        run: npm run test

