name: Build Organization Administration component with docker and test it
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build docker image
        run: docker build ./Organization-Administration/ --file ./Organization-Administration/Dockerfile --tag organization-administration:$(date +%s)

  tests:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./Organization-Administration

    steps:
      - uses: actions/checkout@v2

      - name: Install NPM packages
        run: npm ci

      - name: Run eslint checks
        run: npm run lint

      - name: Run unit tests
        run: npm run test

